### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by fenghong66** [lxy764139720/Auto_Attendance#1]
能放到云函数里面执行定时打卡不？
就是把位置坐标写成固定的     实现在云函数里面自动打卡

**Comment by lxy764139720** [comment]
可以使用云函数。坐标位置是根据你上一次打卡的位置确定的，比如你之前一直用手机打卡，那么使用这个程序打卡的位置就是你最后一次手机打卡的位置。当然你也可以自己改提交的json，但是要保证自定义的位置是能够被服务器正确识别的。

**Comment by fenghong66** [comment]
ok，谢谢你，我提交云函数看看吧，希望不会异地，不然被点名就尴尬了
