### ISSUE TITLE
个人信息获取失败

### ISSUE THREAD

**Issue by lzmoonlight** [lxy764139720/Auto_Attendance#11]
错误信息如下：
```bash
Traceback (most recent call last):
  File "auto.py", line 130, in <module>
    main(args.username, args.password)
  File "auto.py", line 113, in main
    dk.get_info()
  File "auto.py", line 71, in get_info
    jsontext = re.findall(r'def = {[\s\S]*?};', html)[0]
IndexError: list index out of range
⠋ 正在获取个人信息...
Error: Process completed with exit code 1.
```

**Comment by lxy764139720** [comment]
您好，请检查账号和密码是否正确。请在这里http://ca.its.csu.edu.cn/Home/Login/215尝试用你在仓库中输入的账号密码进行登陆。期待您的回复。

**Comment by lxy764139720** [comment]
您好，请检查账号和密码是否正确。请在![信网中心](http://ca.its.csu.edu.cn/Home/Login/215)尝试用你在仓库中输入的账号密码进行登陆。期待您的回复。

**Comment by lxy764139720** [comment]
您好，请检查账号和密码是否正确。请在[信网中心](http://ca.its.csu.edu.cn/Home/Login/215)尝试用你在仓库中输入的账号密码进行登陆。期待您的回复。

**Comment by lzmoonlight** [comment]
账户密码无误，显示已登录，且在获取个人信息，但是出现了上述错误，可见下图
https://sm.ms/image/KO7ZdLcESogha5s

**Comment by lxy764139720** [comment]
我翻了最近fork的用户的actions，发现他们的运行都正常。暂时不清楚问题出现的原因，提供两个可能的解决措施供参考：
1、在http://ca.its.csu.edu.cn/Home/Login/215网址尝试登陆，确认账号密码正确
2、手动获取定位地点进行一次打卡，再重新启动actions
如果还是不行的话，试试删除仓库重新操作。

**Comment by lxy764139720** [comment]
您好，我注意到您最近的打卡成功了，能否告知是如何解决的吗？

**Comment by lzmoonlight** [comment]
我没做什么，莫名其妙就可以了
