### ISSUE TITLE
运行时显示NameError: name 'null' is not defined

### ISSUE THREAD

**Issue by satanruiko** [lxy764139720/Auto_Attendance#16]
67 `geo_obj = eval(geo_text)['addressComponent']`
geo_text中含有null,（`"accuracy":null`）
python无法处理。

**Comment by satanruiko** [comment]
在开头将null定义为None

**Comment by lxy764139720** [comment]
![image](https://user-images.githubusercontent.com/45818075/103326638-48ab6100-4a8c-11eb-83ff-642d4cea88eb.png)
你好我这里不是null呢。根据网页中的vue代码，当用户点击拒绝提供位置信息时accuracy才会是null。另外请仔细阅读issue区使用说明，关于使用过程中出现的问题请反馈到discussions区哦，谢谢！
