### ISSUE TITLE
关于五一节后无法自动打卡情况的相关说明

### ISSUE THREAD

**Issue by lxy764139720** [lxy764139720/Auto_Attendance#31]
自从五一学校新增了疫苗相关打卡信息后，原来的信息门户统一认证平台页面无法登入。

由于本人最近学业繁忙，各种事项较多，无法及时修复相关问题，很抱歉的通知各位用户本项目暂时无法使用，预计修复时间未知（可能要到期末之后闲下来才能修复），请自行选择其他代打卡服务。

同时也欢迎有相关开发经验的同学向本项目提交PR，帮助修复相关问题。

---
### 最后再次对相关问题给您造成的不便表示歉意！

**Comment by M-2Pac** [comment]
之前刚新增项目的几天，我没注意到，依旧是可以打卡的。但貌似自动打卡没有填写那几项。手动填写一次后，就打不了了。感觉这样可能不是登录页面的问题？

**Comment by Kirorr** [comment]
登录认证界面改了，变成：
https://ca.csu.edu.cn/authserver/login?service=https%3A%2F%2Fwxxy.csu.edu.cn%2Fa_csu%2Fapi%2Fcas%2Findex%3Fredirect%3Dhttps%253A%252F%252Fwxxy.csu.edu.cn%252Fsite%252FapplicationSquare%252Findex%253Fsid%253D1%26from%3Dwap

**Comment by lxy764139720** [comment]
> 之前刚新增项目的几天，我没注意到，依旧是可以打卡的。但貌似自动打卡没有填写那几项。手动填写一次后，就打不了了。感觉这样可能不是登录页面的问题？

不是你的原因，是登录认证页面无法进入了

**Comment by lxy764139720** [comment]
> 登录认证界面改了，变成：
> https://ca.csu.edu.cn/authserver/login?service=https%3A%2F%2Fwxxy.csu.edu.cn%2Fa_csu%2Fapi%2Fcas%2Findex%3Fredirect%3Dhttps%253A%252F%252Fwxxy.csu.edu.cn%252Fsite%252FapplicationSquare%252Findex%253Fsid%253D1%26from%3Dwap

这个网页已经试过了，不大行

**Comment by zhwdzh** [comment]
谢谢学长啊，用了快一年了很是方便，要不是没学python，我都想修复下了，学长是研究生吗 @lxy764139720

**Comment by What-a-mess** [comment]
研究了一下，新的单点登录系统在前端用了AES加密，所以需要在代码里面加上对应的加密部分，无奈vi生成的方式实在看不懂，感觉用Node.js直接调用加密模块会简单很多

**Comment by hidragonma** [comment]
> 研究了一下，新的单点登录系统在前端用了AES加密，所以需要在代码里面加上对应的加密部分，无奈vi生成的方式实在看不懂，感觉用Node.js直接调用加密模块会简单很多

是的，单点登录改成CAS方式，我看看明天能不能抽时间修复下😄

**Comment by lxy764139720** [comment]
> 研究了一下，新的单点登录系统在前端用了AES加密，所以需要在代码里面加上对应的加密部分，无奈vi生成的方式实在看不懂，感觉用Node.js直接调用加密模块会简单很多



> > 研究了一下，新的单点登录系统在前端用了AES加密，所以需要在代码里面加上对应的加密部分，无奈vi生成的方式实在看不懂，感觉用Node.js直接调用加密模块会简单很多
> 
> 是的，单点登录改成CAS方式，我看看明天能不能抽时间修复下😄

大佬们tql，欢迎pr

**Comment by hidragonma** [comment]
#32 Github Actions测试修复代码过程中，一直卡在Waiting for pending jobs状态。还不知道是否是配置文件是否存在问题（对Git Actions不了解）。 @lxy764139720

**Comment by lxy764139720** [comment]
> #32 Github Actions测试修复代码过程中，一直卡在Waiting for pending jobs状态。还不知道配置文件是否存在问题（对Git Actions不了解）。 @lxy764139720

可以在本机跑起来吗？github actions的问题可以截个图给我看看。

**Comment by hidragonma** [comment]
> > #32 Github Actions测试修复代码过程中，一直卡在Waiting for pending jobs状态。还不知道配置文件是否存在问题（对Git Actions不了解）。 @lxy764139720
> 
> 可以在本机跑起来吗？github actions的问题可以截个图给我看看。

本机可以打卡。我测试了两个账号，由于两个账号今天都打过卡了，所以显示的是今天已打卡。

**Comment by lxy764139720** [comment]
> > > #32 Github Actions测试修复代码过程中，一直卡在Waiting for pending jobs状态。还不知道配置文件是否存在问题（对Git Actions不了解）。 @lxy764139720
> > 
> > 
> > 可以在本机跑起来吗？github actions的问题可以截个图给我看看。
> 
> 本机可以打卡。我测试了两个账号，由于两个账号今天都打过卡了，所以显示的是今天已打卡。

那你直接把py文件提一个pr给这个仓库就行，actions文件不用管，我来看一下

**Comment by hidragonma** [comment]
> > > > #32 Github Actions测试修复代码过程中，一直卡在Waiting for pending jobs状态。还不知道配置文件是否存在问题（对Git Actions不了解）。 @lxy764139720
> > > 
> > > 
> > > 可以在本机跑起来吗？github actions的问题可以截个图给我看看。
> > 
> > 
> > 本机可以打卡。我测试了两个账号，由于两个账号今天都打过卡了，所以显示的是今天已打卡。
> 
> 那你直接把py文件提一个pr给这个仓库就行，actions文件不用管，我来看一下

#32 就是这个

**Comment by lxy764139720** [comment]
> > > > > #32 Github Actions测试修复代码过程中，一直卡在Waiting for pending jobs状态。还不知道配置文件是否存在问题（对Git Actions不了解）。 @lxy764139720
> > > > 
> > > > 
> > > > 可以在本机跑起来吗？github actions的问题可以截个图给我看看。
> > > 
> > > 
> > > 本机可以打卡。我测试了两个账号，由于两个账号今天都打过卡了，所以显示的是今天已打卡。
> > 
> > 
> > 那你直接把py文件提一个pr给这个仓库就行，actions文件不用管，我来看一下
> 
> #32 就是这个

我也是同样的问题，暂时不知道原因，还没有时间仔细研究，我贴一个网上看到的帖子：https://github.community/t/github-action-stuck-at-queue/16869/108

**Comment by hidragonma** [comment]
> > > > > > #32 Github Actions测试修复代码过程中，一直卡在Waiting for pending jobs状态。还不知道配置文件是否存在问题（对Git Actions不了解）。 @lxy764139720
> > > > > 
> > > > > 
> > > > > 可以在本机跑起来吗？github actions的问题可以截个图给我看看。
> > > > 
> > > > 
> > > > 本机可以打卡。我测试了两个账号，由于两个账号今天都打过卡了，所以显示的是今天已打卡。
> > > 
> > > 
> > > 那你直接把py文件提一个pr给这个仓库就行，actions文件不用管，我来看一下
> > 
> > 
> > #32 就是这个
> 
> 我也是同样的问题，暂时不知道原因，还没有时间仔细研究，我贴一个网上看到的帖子：https://github.community/t/github-action-stuck-at-queue/16869/108

嗯嗯 应该是Github CICD系统的任务队列阻塞了。今天早上试了下，可以自动打卡。

**Comment by lxy764139720** [comment]
> > > > > > > #32 Github Actions测试修复代码过程中，一直卡在Waiting for pending jobs状态。还不知道配置文件是否存在问题（对Git Actions不了解）。 @lxy764139720
> > > > > > 
> > > > > > 
> > > > > > 可以在本机跑起来吗？github actions的问题可以截个图给我看看。
> > > > > 
> > > > > 
> > > > > 本机可以打卡。我测试了两个账号，由于两个账号今天都打过卡了，所以显示的是今天已打卡。
> > > > 
> > > > 
> > > > 那你直接把py文件提一个pr给这个仓库就行，actions文件不用管，我来看一下
> > > 
> > > 
> > > #32 就是这个
> > 
> > 
> > 我也是同样的问题，暂时不知道原因，还没有时间仔细研究，我贴一个网上看到的帖子：https://github.community/t/github-action-stuck-at-queue/16869/108
> 
> 嗯嗯 应该是Github CICD系统的任务队列阻塞了。今天早上试了下，可以自动打卡。

是的我这边也可以打卡了，感谢贡献代码

**Comment by Kirorr** [comment]
> 登录认证界面改了，变成：
> https://ca.csu.edu.cn/authserver/login?service=https%3A%2F%2Fwxxy.csu.edu.cn%2Fa_csu%2Fapi%2Fcas%2Findex%3Fredirect%3Dhttps%253A%252F%252Fwxxy.csu.edu.cn%252Fsite%252FapplicationSquare%252Findex%253Fsid%253D1%26from%3Dwap

这个网站好像也可以：
https://ca.csu.edu.cn/authserver/login?service=http%3A%2F%2Fmy.csu.edu.cn%2F

**Comment by lxy764139720** [comment]
此bug以被[@hidragonma](https://github.com/hidragonma)修复，感谢贡献代码！
