### ISSUE TITLE
关于info 找cookie那

### ISSUE THREAD

**Issue by Awesomefang** [lxy764139720/Auto_Attendance#4]
info  是在哪里找啊  能不能来个图片 QAQ  小白一名

**Comment by Awesomefang** [comment]
> info 是在哪里找啊 能不能来个图片 QAQ 小白一名

这是我在ie浏览器找的：name,value,domain,path,expires,sameSite,httpOnly,secure
eai-sess,4dquesbt9hqsj42lbsfk2hjib7,wxxy.csu.edu.cn,/,"Thu, 17 Sep 2020 03:31:17 GMT",None,true,false
name,value,domain,path,expires,sameSite,httpOnly,secure
eai-sess,4dquesbt9hqsj42lbsfk2hjib7,wxxy.csu.edu.cn,/,"Thu, 17 Sep 2020 03:31:17 GMT",None,true,false
然后复制的项目   能不能告诉我哪里才是有用的

**Comment by lxy764139720** [comment]
![](https://raw.githubusercontent.com/lxy764139720/Figurebed/master/img/20200410115438.jpg)
readme中有图片，在控制台Network页面的左侧。

**Comment by Awesomefang** [comment]
![1](https://user-images.githubusercontent.com/69832484/90516805-1bbe7780-e197-11ea-8ebb-b73a40db2932.png)
![2](https://user-images.githubusercontent.com/69832484/90516884-37298280-e197-11ea-8de8-ee10b6f044fc.png)
我加了图片 不知道能不能看  我的readme 中的图片加载失败

**Comment by lxy764139720** [comment]
你往下面翻找一下，或者尝试换用chrome浏览器试一下
