### ISSUE TITLE
actions run into error

### ISSUE THREAD

**Issue by nye0** [lxy764139720/Auto_Attendance#5]
Hi,
Thank you for making this great tool, it work well for about a month, but this morning it runs into an error.
`Traceback (most recent call last):
  File "auto.py", line 116, in <module>
    main(args.username, args.password, args.eai_sess, args.UUkey)
  File "auto.py", line 93, in main
    dk.login()
  File "auto.py", line 43, in login
    self.cookie2 = res2.headers['Set-Cookie'].split(";")[0]
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'set-cookie'
⠙ 登录到中南大学信息门户...
##[error]Process completed with exit code 1.`
Could you help me figure out what happen?
It would be awesome if you could add a function that if the auto attend fail, the program will send an email  as a remainer.
Thank you!
Ningrong

**Comment by lxy764139720** [comment]
您好，今早我也收到了同样的错误。从我编写这个程序以来，打卡网站的cookie和打卡格式经过了多次的变动，为此我也进行了多次修改。由于我最近正在准备考试，因此不能特别及时地处理问题，请见谅。今晚我将会查看并且尝试修复此问题，未来几天内请您关注本条issue的通知。在收到通知前麻烦您先手动打卡一下，顺利的话问题会很快被修复。关于发送邮件的问题，我认为暂时无此必要，github-actions提供了良好的通知。请将您的github通知绑定到一个常用邮箱上，qq邮箱可以通过微信关注其公众号服务来获取邮件通知。当github-actions运行出现错误时，例如今早的情况，您将会立即收到邮件通知。祝使用愉快！🎉🎉

**Comment by nye0** [comment]
哇，谢谢大神！祝考试顺利！

**Comment by lxy764139720** [comment]
您好，今天早晨的打卡又自动变好了，我又试了一下确实没有问题。那就先暂时这样，如果再出现类似问题，我再检查。
