### ISSUE TITLE
A problem encountered when running the project

### ISSUE THREAD

**Issue by zhenyuw96** [lxy764139720/Auto_Attendance#9]
I forked the project as instructed and added the secrets. However, when I was tryna run it, there was always an error message popping up, which is pasted below:
**Traceback (most recent call last):
  File "auto.py", line 116, in <module>
    main(args.username, args.password, args.eai_sess, args.UUkey)
  File "auto.py", line 97, in main
    dk.get_info()
  File "auto.py", line 60, in get_info
    geo_obj = eval(geo_text)['addressComponent']
  File "<string>", line 1, in <module>
NameError: name 'null' is not defined
⠸ 正在获取个人信息...
Error: Process completed with exit code 1.**

All the secrets were true and I did not make any changes to the code of the project. Could you please help me figure this out? Thank you very much!

**Comment by lxy764139720** [comment]
你好，可以发一下报错截图吗

**Comment by zhenyuw96** [comment]
------------------&nbsp;Original&nbsp;------------------

**Comment by lxy764139720** [comment]
看不到图片啊，你发我邮箱吧lxy764139720@gmail.com

**Comment by lxy764139720** [comment]
该问题已解决，解决方法为手动打卡获取定位，之后重新运行本项目。
